package common

/*
Generated using mavgen - https://github.com/ArduPilot/pymavlink/

Copyright 2019 queue-b <https://github.com/queue-b>

Permission is hereby granted, free of charge, to any person obtaining a copy
of the generated software (the "Generated Software"), to deal
in the Generated Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Generated Software, and to permit persons to whom the Generated
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Generated Software.

THE GENERATED SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE GENERATED SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE GENERATED SOFTWARE.
*/

import (
	"bytes"
	"encoding/binary"
)

/*RadioStatus Status generated by radio and injected into MAVLink stream. */
type RadioStatus struct {
	/*ReadVersion indicates the wire format the packet was read from */
	ReadVersion int
	/*Rxerrors Count of radio packet receive errors (since boot). */
	Rxerrors uint16
	/*Fixed Count of error corrected radio packets (since boot). */
	Fixed uint16
	/*Rssi Local (message sender) recieved signal strength indication in device-dependent units/scale. Values: [0-254], 255: invalid/unknown. */
	Rssi uint8
	/*Remrssi Remote (message receiver) signal strength indication in device-dependent units/scale. Values: [0-254], 255: invalid/unknown. */
	Remrssi uint8
	/*Txbuf Remaining free transmitter buffer space. */
	Txbuf uint8
	/*Noise Local background noise level. These are device dependent RSSI values (scale as approx 2x dB on SiK radios). Values: [0-254], 255: invalid/unknown. */
	Noise uint8
	/*Remnoise Remote background noise level. These are device dependent RSSI values (scale as approx 2x dB on SiK radios). Values: [0-254], 255: invalid/unknown. */
	Remnoise uint8
}

// Read sets the field values of the message from the raw message payload
func (m *RadioStatus) Read(version int, payload []byte) (err error) {
	reader := bytes.NewReader(payload)

	m.ReadVersion = version
	err = binary.Read(reader, binary.LittleEndian, &m.Rxerrors)
	if err != nil {
		return
	}

	err = binary.Read(reader, binary.LittleEndian, &m.Fixed)
	if err != nil {
		return
	}

	err = binary.Read(reader, binary.LittleEndian, &m.Rssi)
	if err != nil {
		return
	}

	err = binary.Read(reader, binary.LittleEndian, &m.Remrssi)
	if err != nil {
		return
	}

	err = binary.Read(reader, binary.LittleEndian, &m.Txbuf)
	if err != nil {
		return
	}

	err = binary.Read(reader, binary.LittleEndian, &m.Noise)
	if err != nil {
		return
	}

	err = binary.Read(reader, binary.LittleEndian, &m.Remnoise)
	if err != nil {
		return
	}

	return
}

// Write encodes the field values of the message to a byte array
func (m *RadioStatus) Write(version int) ([]byte, error) {
	var buffer bytes.Buffer
	var err error
	err = binary.Write(&buffer, binary.LittleEndian, m.Rxerrors)
	if err != nil {
		return nil, err
	}

	err = binary.Write(&buffer, binary.LittleEndian, m.Fixed)
	if err != nil {
		return nil, err
	}

	err = binary.Write(&buffer, binary.LittleEndian, m.Rssi)
	if err != nil {
		return nil, err
	}

	err = binary.Write(&buffer, binary.LittleEndian, m.Remrssi)
	if err != nil {
		return nil, err
	}

	err = binary.Write(&buffer, binary.LittleEndian, m.Txbuf)
	if err != nil {
		return nil, err
	}

	err = binary.Write(&buffer, binary.LittleEndian, m.Noise)
	if err != nil {
		return nil, err
	}

	err = binary.Write(&buffer, binary.LittleEndian, m.Remnoise)
	if err != nil {
		return nil, err
	}

	return buffer.Bytes(), nil
}
